### ISSUE TITLE
A question about experimental reproduction

### ISSUE THREAD

**Issue by wzhlovesleep** [RUB-SysSec/dompteur#3]
Hello, author, I am very interested in your composition and hope to reproduce your experiment. However, due to some conditions, docker cannot be used. Can you provide a version that does not need to be implemented by docker?

**Comment by thorsten-e** [comment]
Hi! We tested the attack on Ubuntu 18.04 with Cuda 10.0. You should be able to setup the correct environment by repeating the steps in the Dockerfile (cf. `https://github.com/RUB-SysSec/dompteur/blob/main/Dockerfile`).
