### ISSUE TITLE
RuntimeError: Container failed to build

### ISSUE THREAD

**Issue by wzhlovesleep** [RUB-SysSec/dompteur#4]
I run the dockerfile and install the dompteur image, and then I run the following instructions in the container
`python3 /root/dompteur/src/decode.py --models dompteur_f825_phi.None_bandpass.None-None --experiments resultSet `
The following errors were reported
`[+] build container
    log @ /root/dompteur/docker.log.txt
    -> Container failed to build
Traceback (most recent call last):
  File "/root/dompteur/src/decode.py", line 49, in <module>
    Kaldi.build_container(BASE_DIR)
  File "/root/dompteur/src/kaldi.py", line 43, in build_container
    raise RuntimeError(f"Container failed to build\n{' '*14}log @ {docker_log}")
RuntimeError: Container failed to build
              log @ /root/dompteur/docker.log.txt
`

**Comment by thorsten-e** [comment]
Hi! The scripts in `dompteur/src` are convenience scripts to instrument the docker container containing the full kaldi installation. To resolve your issue, you basically need to run the script on the host (and not in the container) and the script itself will then spin-up the container for you. Best, Thorsten
